// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUoH4G2EA93uM2AkqQ3JjNByRFyVTzUaw',
    appId: '1:577436340001:web:7de08419721d57a2973860',
    messagingSenderId: '577436340001',
    projectId: 'petuno-app-origin',
    authDomain: 'petuno-app-origin.firebaseapp.com',
    storageBucket: 'petuno-app-origin.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTaX91sUNvV91As1VAKZ4WZaEJw6AN8iA',
    appId: '1:577436340001:android:e6ca1c8f69a3e7c1973860',
    messagingSenderId: '577436340001',
    projectId: 'petuno-app-origin',
    storageBucket: 'petuno-app-origin.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBItErhG5ZRxSpaXq4FaVVUFy06E19hr20',
    appId: '1:577436340001:ios:cacf187ecf58a6f0973860',
    messagingSenderId: '577436340001',
    projectId: 'petuno-app-origin',
    storageBucket: 'petuno-app-origin.firebasestorage.app',
    iosBundleId: 'com.example.petunoApp',
  );
}
